[database]
    name     = "vulcanize_public"
    hostname = "localhost"
    port     = 5432

[client]
    ipcPath  = "https://mainnet.infura.io/J5Vd2fRtGsw0zZ0Ov3BL"

[exporter]
    home     = "github.com/vulcanize/vulcanizedb"
    name     = "ENSEventTransformerExporter"
    save     = false
    transformerNames = [
        "auction_started",
        "bid_revealed",
        "hash_invalidated",
        "hash_registered",
        "hash_released",
        "new_bid",
        "new_owner",
        "new_resolver",
        "new_ttl",
        "transfer",
        "abi_changed",
        "addr_changed",
        "content_changed",
        "contenthash_changed",
        "multihash_changed",
        "pubkey_changed",
        "text_changed"
    ]
    [exporter.auction_started]
        path = "transformers/registar/auction_started/initializer"
        type = "eth_event"
        repository = "github.com/vulcanize/ens_transformers"
        migrations = "db/migrations"
    [exporter.bid_revealed]
        path = "transformers/registar/bid_revealed/initializer"
        type = "eth_event"
        repository = "github.com/vulcanize/ens_transformers"
        migrations = "db/migrations"
    [exporter.hash_invalidated]
        path = "transformers/registar/hash_invalidated/initializer"
        type = "eth_event"
        repository = "github.com/vulcanize/ens_transformers"
        migrations = "db/migrations"
    [exporter.hash_registered]
        path = "transformers/registar/hash_registered/initializer"
        type = "eth_event"
        repository = "github.com/vulcanize/ens_transformers"
        migrations = "db/migrations"
    [exporter.hash_released]
        path = "transformers/registar/hash_released/initializer"
        type = "eth_event"
        repository = "github.com/vulcanize/ens_transformers"
        migrations = "db/migrations"
    [exporter.new_bid]
        path = "transformers/registar/new_bid/initializer"
        type = "eth_event"
        repository = "github.com/vulcanize/ens_transformers"
        migrations = "db/migrations"
    [exporter.new_owner]
        path = "transformers/registry/new_owner/initializer"
        type = "eth_event"
        repository = "github.com/vulcanize/ens_transformers"
        migrations = "db/migrations"
    [exporter.new_resolver]
        path = "transformers/registry/new_resolver/initializer"
        type = "eth_event"
        repository = "github.com/vulcanize/ens_transformers"
        migrations = "db/migrations"
    [exporter.new_ttl]
        path = "transformers/registry/new_ttl/initializer"
        type = "eth_event"
        repository = "github.com/vulcanize/ens_transformers"
        migrations = "db/migrations"
    [exporter.transfer]
        path = "transformers/registry/transfer/initializer"
        type = "eth_event"
        repository = "github.com/vulcanize/ens_transformers"
        migrations = "db/migrations"
    [exporter.abi_changed]
        path = "transformers/resolver/abi_changed/initializer"
        type = "eth_event"
        repository = "github.com/vulcanize/ens_transformers"
        migrations = "db/migrations"
    [exporter.addr_changed]
        path = "transformers/resolver/addr_changed/initializer"
        type = "eth_event"
        repository = "github.com/vulcanize/ens_transformers"
        migrations = "db/migrations"
    [exporter.content_changed]
        path = "transformers/resolver/content_changed/initializer"
        type = "eth_event"
        repository = "github.com/vulcanize/ens_transformers"
        migrations = "db/migrations"
    [exporter.contenthash_changed]
        path = "transformers/resolver/contenthash_changed/initializer"
        type = "eth_event"
        repository = "github.com/vulcanize/ens_transformers"
        migrations = "db/migrations"
    [exporter.multihash_changed]
        path = "transformers/resolver/multihash_changed/initializer"
        type = "eth_event"
        repository = "github.com/vulcanize/ens_transformers"
        migrations = "db/migrations"
    [exporter.pubkey_changed]
        path = "transformers/resolver/pubkey_changed/initializer"
        type = "eth_event"
        repository = "github.com/vulcanize/ens_transformers"
        migrations = "db/migrations"
    [exporter.text_changed]
        path = "transformers/resolver/text_changed/initializer"
        type = "eth_event"
        repository = "github.com/vulcanize/ens_transformers"
        migrations = "db/migrations"

[contract]
    [contract.address]
            registry = "0x314159265dD8dbb310642f98f50C066173C1259b"
            resolver = "0x1da022710dF5002339274AaDEe8D58218e9D6AB5"
            registar = "0x6090A6e47849629b7245Dfa1Ca21D94cd15878Ef"
    [contract.abi]
            registry = '[{"constant":true,"inputs":[{"name":"node","type":"bytes32"}],"name":"resolver","outputs":[{"name":"","type":"address"}],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"node","type":"bytes32"}],"name":"owner","outputs":[{"name":"","type":"address"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"node","type":"bytes32"},{"name":"label","type":"bytes32"},{"name":"owner","type":"address"}],"name":"setSubnodeOwner","outputs":[],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"node","type":"bytes32"},{"name":"ttl","type":"uint64"}],"name":"setTTL","outputs":[],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"node","type":"bytes32"}],"name":"ttl","outputs":[{"name":"","type":"uint64"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"node","type":"bytes32"},{"name":"resolver","type":"address"}],"name":"setResolver","outputs":[],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"node","type":"bytes32"},{"name":"owner","type":"address"}],"name":"setOwner","outputs":[],"payable":false,"type":"function"},{"anonymous":false,"inputs":[{"indexed":true,"name":"node","type":"bytes32"},{"indexed":false,"name":"owner","type":"address"}],"name":"Transfer","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"node","type":"bytes32"},{"indexed":true,"name":"label","type":"bytes32"},{"indexed":false,"name":"owner","type":"address"}],"name":"NewOwner","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"node","type":"bytes32"},{"indexed":false,"name":"resolver","type":"address"}],"name":"NewResolver","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"node","type":"bytes32"},{"indexed":false,"name":"ttl","type":"uint64"}],"name":"NewTTL","type":"event"}]'
            resolver = '[{"constant":true,"inputs":[{"name":"interfaceID","type":"bytes4"}],"name":"supportsInterface","outputs":[{"name":"","type":"bool"}],"payable":false,"type":"function"},{"anonymous":false,"inputs":[{"indexed":true,"name":"node","type":"bytes32"},{"indexed":false,"name":"a","type":"address"}],"name":"AddrChanged","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"node","type":"bytes32"},{"indexed":false,"name":"hash","type":"bytes32"}],"name":"ContentChanged","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"node","type":"bytes32"},{"indexed":false,"name":"name","type":"string"}],"name":"NameChanged","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"node","type":"bytes32"},{"indexed":true,"name":"contentType","type":"uint256"}],"name":"ABIChanged","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"node","type":"bytes32"},{"indexed":false,"name":"x","type":"bytes32"},{"indexed":false,"name":"y","type":"bytes32"}],"name":"PubkeyChanged","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"node","type":"bytes32"},{"indexed":false,"name":"indexedKey","type":"string"},{"indexed":false,"name":"key","type":"string"}],"name":"TextChanged","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"node","type":"bytes32"},{"indexed":false,"name":"hash","type":"bytes"}],"name":"MultihashChanged","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"node","type":"bytes32"},{"indexed":false,"name":"hash","type":"bytes"}],"name":"ContenthashChanged","type":"event"}]'
            registar = '[{"constant":false,"inputs":[{"name":"_hash","type":"bytes32"}],"name":"releaseDeed","outputs":[],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"_hash","type":"bytes32"}],"name":"getAllowedTime","outputs":[{"name":"timestamp","type":"uint256"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"unhashedName","type":"string"}],"name":"invalidateName","outputs":[],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"hash","type":"bytes32"},{"name":"owner","type":"address"},{"name":"value","type":"uint256"},{"name":"salt","type":"bytes32"}],"name":"shaBid","outputs":[{"name":"sealedBid","type":"bytes32"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"bidder","type":"address"},{"name":"seal","type":"bytes32"}],"name":"cancelBid","outputs":[],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"_hash","type":"bytes32"}],"name":"entries","outputs":[{"name":"","type":"uint8"},{"name":"","type":"address"},{"name":"","type":"uint256"},{"name":"","type":"uint256"},{"name":"","type":"uint256"}],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"ens","outputs":[{"name":"","type":"address"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"_hash","type":"bytes32"},{"name":"_value","type":"uint256"},{"name":"_salt","type":"bytes32"}],"name":"unsealBid","outputs":[],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"_hash","type":"bytes32"}],"name":"transferRegistrars","outputs":[],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"","type":"address"},{"name":"","type":"bytes32"}],"name":"sealedBids","outputs":[{"name":"","type":"address"}],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"_hash","type":"bytes32"}],"name":"state","outputs":[{"name":"","type":"uint8"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"_hash","type":"bytes32"},{"name":"newOwner","type":"address"}],"name":"transfer","outputs":[],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"_hash","type":"bytes32"},{"name":"_timestamp","type":"uint256"}],"name":"isAllowed","outputs":[{"name":"allowed","type":"bool"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"_hash","type":"bytes32"}],"name":"finalizeAuction","outputs":[],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"registryStarted","outputs":[{"name":"","type":"uint256"}],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"launchLength","outputs":[{"name":"","type":"uint32"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"sealedBid","type":"bytes32"}],"name":"newBid","outputs":[],"payable":true,"type":"function"},{"constant":false,"inputs":[{"name":"labels","type":"bytes32[]"}],"name":"eraseNode","outputs":[],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"_hashes","type":"bytes32[]"}],"name":"startAuctions","outputs":[],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"hash","type":"bytes32"},{"name":"deed","type":"address"},{"name":"registrationDate","type":"uint256"}],"name":"acceptRegistrarTransfer","outputs":[],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"_hash","type":"bytes32"}],"name":"startAuction","outputs":[],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"rootNode","outputs":[{"name":"","type":"bytes32"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"hashes","type":"bytes32[]"},{"name":"sealedBid","type":"bytes32"}],"name":"startAuctionsAndBid","outputs":[],"payable":true,"type":"function"},{"inputs":[{"name":"_ens","type":"address"},{"name":"_rootNode","type":"bytes32"},{"name":"_startDate","type":"uint256"}],"payable":false,"type":"constructor"},{"anonymous":false,"inputs":[{"indexed":true,"name":"hash","type":"bytes32"},{"indexed":false,"name":"registrationDate","type":"uint256"}],"name":"AuctionStarted","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"hash","type":"bytes32"},{"indexed":true,"name":"bidder","type":"address"},{"indexed":false,"name":"deposit","type":"uint256"}],"name":"NewBid","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"hash","type":"bytes32"},{"indexed":true,"name":"owner","type":"address"},{"indexed":false,"name":"value","type":"uint256"},{"indexed":false,"name":"status","type":"uint8"}],"name":"BidRevealed","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"hash","type":"bytes32"},{"indexed":true,"name":"owner","type":"address"},{"indexed":false,"name":"value","type":"uint256"},{"indexed":false,"name":"registrationDate","type":"uint256"}],"name":"HashRegistered","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"hash","type":"bytes32"},{"indexed":false,"name":"value","type":"uint256"}],"name":"HashReleased","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"hash","type":"bytes32"},{"indexed":true,"name":"name","type":"string"},{"indexed":false,"name":"value","type":"uint256"},{"indexed":false,"name":"registrationDate","type":"uint256"}],"name":"HashInvalidated","type":"event"}]'
    [contract.deployment-block]
            registry = 3327417
            resolver = 3648359
            registar = 3605331

